create_config:
	cp config_options.json config.json

run:
	pipenv run python main.py config.json > output/output.txt

crossing:
	pipenv run python crossing_method_generator.py

mutation:
	pipenv run python mutation_method_generator.py

selection:
	pipenv run python selection_method_generator.py